# Generated by Django 2.2.6 on 2020-01-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='birthday',
            field=models.CharField(max_length=15),
        ),
    ]
