# Generated by Django 2.2.6 on 2020-01-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_auto_20200105_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='birthday',
            field=models.DateField(),
        ),
    ]
