# Generated by Django 2.2.6 on 2020-01-07 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_auto_20200107_0442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='birthday',
        ),
    ]
