# Generated by Django 2.2.6 on 2020-01-07 04:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0005_remove_friend_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2020, 1, 7, 4, 57, 52, 610779, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
