# Generated by Django 2.2 on 2020-03-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0007_auto_20200111_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='test',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
