# Generated by Django 2.2 on 2020-03-05 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0008_friend_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='test',
        ),
    ]
